# Generated by Django 3.2.16 on 2025-02-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='posts',
        ),
    ]
