# Generated by Django 3.2.16 on 2025-02-16 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250215_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 6, 6, 31, 323642, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
