# Generated by Django 3.2.16 on 2025-02-16 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20250216_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
